# Generated by Django 5.1.6 on 2025-02-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckstop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='truckstop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='truckstop',
            name='rack_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckstop',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['retail_price'], name='api_truckst_retail__d83b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='truckstop',
            index=models.Index(fields=['latitude', 'longitude'], name='api_truckst_latitud_86adc8_idx'),
        ),
    ]
